#!/usr/bin/env python3
"""
Scenario-Adaptive Synthetic Data Validation CLI
================================================
Validates synthesized datasets with scenario-adaptive checks:
- Code-based: distribution matching (KS, chi-square), schema conformance,
  value range, correlation, sentinel re-detection, vocabulary overlap
- LLM-as-judge: rubric-based quality scoring with cost-aware sampling
- Auto: detects column type and selects approach automatically

The validation approach per column is either specified in a criteria JSON
(dynamically generated by the coding agent) or determined automatically.

Usage:
    python validate_synthetic.py INPUT_PATH REPORT_PATH \\
      [--original-path ORIGINAL_PATH] \\
      [--criteria-json CRITERIA_PATH] \\
      [--sentinel-patterns '["X","N/A"]'] \\
      [--columns col1,col2] \\
      [--sample-size N] [--max-cost FLOAT] \\
      [--agent-yaml YAML_PATH] [--model MODEL]

Criteria JSON format (agent-generated, per-column):
{
  "columns": {
    "price": {
      "approach": "code_based",
      "checks": {
        "value_range": {"min": 0, "max": 100000},
        "distribution_match": {"test": "ks", "min_pvalue": 0.05},
        "null_rate": {"max": 0.01}
      }
    },
    "definition": {
      "approach": "llm_judge",
      "rubric": "Rate: accuracy (1-5), completeness (1-5). Pass if all >= 3.",
      "sample_rate": 0.1,
      "pass_threshold": 0.9
    }
  }
}

Report structure:
{
  "success": true,
  "overall_verdict": "PASS",
  "overall_score": 0.92,
  "columns": {
    "price": {
      "approach": "code_based",
      "checks": {...},
      "pass": true,
      "score": 0.98,
      "flagged_rows": [],
      "suggestions": []
    }
  },
  "sentinel_check": {...},
  "summary": {...}
}
"""
# REFERENCE IMPLEMENTATION — Read for patterns, write custom code adapted to your task.

import argparse
import json
import logging
import math
import re
import sys
import time
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

import numpy as np
import pandas as pd

# ──────────────────────────────────────────────────────────────
# Path Setup — import shared utilities
# ──────────────────────────────────────────────────────────────

_SCRIPT_DIR = Path(__file__).resolve().parent
_SKILLS_DIR = _SCRIPT_DIR.parent.parent


def detect_column_types(df):
    """Stub: detect column types in a DataFrame."""
    import pandas as pd
    result = {}
    for col in df.columns:
        if pd.api.types.is_numeric_dtype(df[col]):
            result[col] = "numeric"
        elif pd.api.types.is_bool_dtype(df[col]):
            result[col] = "boolean"
        else:
            n_unique = df[col].nunique()
            n_total = len(df[col].dropna())
            if n_unique <= 20 or (n_total > 0 and n_unique / n_total < 0.05):
                result[col] = "categorical"
            else:
                result[col] = "text"
    return result
def format_error(message, suggestion=None, rows_in=None):
    """Stub: format an error result dict."""
    import sys
    result = {"success": False, "error": message}
    if suggestion:
        result["suggestion"] = suggestion
    if rows_in is not None:
        result["rows_in"] = rows_in
    print(result, file=sys.stderr)
    sys.exit(1)
def format_success(output_path=None, rows_in=0, rows_out=0, summary=None, warnings=None):
    """Stub: format a success result dict. See magic-data-lifecycle SKILL.md for full pattern."""
    return {"success": True, "output_path": output_path, "rows_in": rows_in, "rows_out": rows_out, "summary": summary or {}, "warnings": warnings or []}
def load_dataframe(path, format="auto", **kwargs):
    """Stub: load a DataFrame from path. See magic-data-loading SKILL.md for full pattern."""
    import pandas as pd
    ext = str(path).rsplit(".", 1)[-1].lower()
    fmt = format if format != "auto" else ext
    if fmt == "parquet":
        return pd.read_parquet(path)
    if fmt in ("jsonl", "ndjson"):
        return pd.read_json(path, lines=True)
    if fmt == "json":
        return pd.read_json(path)
    if fmt == "tsv":
        return pd.read_csv(path, sep="\t")
    return pd.read_csv(path)
def output_result(result):
    """Stub: print result JSON and exit."""
    import json, sys
    print(json.dumps(result, indent=2, default=str))
    sys.exit(0 if result.get("success") else 1)

def build_agent(*args, **kwargs):
    """Stub: build an ADK agent — legacy ADK, not available standalone."""
    return None
def resolve_llm_config(*args, **kwargs):
    """Stub: resolve LLM config — legacy ADK, not available standalone."""
    return {}
def run_agent(agent, prompt, session_id=None):
    """Stub: run an ADK agent — legacy ADK, not available standalone."""
    return ""
class CostAccumulator:
    """Stub: cost accumulator for LLM calls."""
    def __init__(self, max_cost=None):
        self.max_cost = max_cost
        self.total_usd = 0.0
        self.call_count = 0
        self.costs_by_model = {}
    def estimate_cost(self, prompt_tokens=0, completion_tokens=0, model=""):
        return 0.0
    def check_budget(self, estimated_cost):
        if self.max_cost is None:
            return True
        return self.total_usd + estimated_cost <= self.max_cost
    def summary(self):
        return {"total_usd": self.total_usd, "call_count": self.call_count}
class CostLimitExceeded(Exception):
    def __init__(self, actual=0.0, limit=0.0):
        self.actual = actual
        self.limit = limit
        super().__init__(f"Cost limit exceeded: ${actual:.4f} > ${limit:.4f}")

try:
    from synthesis_utils import (
        check_value_range,
        chi_square_test,
        detect_sentinels,
        ks_test,
        sanitize_row_for_prompt,
        vocabulary_overlap,
    )
except ImportError:
    def check_value_range(series, min_val=None, max_val=None):
        """Stub: check that numeric values are within range."""
        import pandas as pd
        numeric = pd.to_numeric(series.dropna(), errors="coerce").dropna()
        violations = []
        if min_val is not None:
            below = numeric[numeric < min_val]
            if len(below) > 0:
                violations.append({"type": "below_min", "limit": min_val, "min_observed": float(below.min())})
        if max_val is not None:
            above = numeric[numeric > max_val]
            if len(above) > 0:
                violations.append({"type": "above_max", "limit": max_val, "max_observed": float(above.max())})
        return {"pass": len(violations) == 0, "violations": violations}
    def chi_square_test(orig_series, synth_series):
        """Stub: chi-square test for categorical distributions."""
        return {"pass": None, "p_value": None, "note": "chi_square_test stub — synthesis_utils not available"}
    def detect_sentinels(series, patterns=None):
        """Stub: detect sentinel values in a series."""
        _SENTINELS = {"N/A", "NA", "n/a", "None", "none", "null", "NULL", "NaN", "nan", "-", "TBD", "X", "x", ""}
        pat_set = set(patterns) if patterns else _SENTINELS
        count = int(series.astype(str).str.strip().isin(pat_set).sum())
        return {"sentinel_count": count, "sentinel_rate": round(count / max(len(series), 1), 4)}
    def ks_test(orig_series, synth_series):
        """Stub: KS test for numeric distributions."""
        return {"pass": None, "p_value": None, "note": "ks_test stub — synthesis_utils not available"}
    def sanitize_row_for_prompt(row, max_length=500):
        """Stub: sanitize a row dict for prompt inclusion."""
        return {k: str(v)[:max_length] for k, v in row.items()}
    def vocabulary_overlap(orig_series, synth_series):
        """Stub: compute vocabulary overlap between two text series."""
        orig_words = set(" ".join(orig_series.dropna().astype(str)).lower().split())
        synth_words = set(" ".join(synth_series.dropna().astype(str)).lower().split())
        intersection = len(orig_words & synth_words)
        union = len(orig_words | synth_words)
        jaccard = round(intersection / union, 4) if union > 0 else 0.0
        return {"jaccard_similarity": jaccard, "orig_vocab_size": len(orig_words), "synth_vocab_size": len(synth_words)}

logger = logging.getLogger(__name__)

# ──────────────────────────────────────────────────────────────
# Constants
# ──────────────────────────────────────────────────────────────

DEFAULT_SENTINEL_PATTERNS = ["X", "N/A", "TBD", "", "???", "NULL", "null", "None", "none", "-"]
DEFAULT_SAMPLE_RATE = 0.1          # 10% for LLM-judge sampling
DEFAULT_PASS_THRESHOLD = 0.9       # 90% pass rate to mark column as PASS
DEFAULT_MIN_KS_PVALUE = 0.05
DEFAULT_MAX_NULL_RATE = 0.05
DEFAULT_MODEL = "openai/gpt-4o-mini"
COST_LIMIT_EXIT_CODE = 2


# ──────────────────────────────────────────────────────────────
# Approach Detection
# ──────────────────────────────────────────────────────────────

def detect_approach(col_name: str, df: pd.DataFrame, col_types: dict) -> str:
    """
    Automatically determine the best validation approach for a column.

    Numeric/datetime/boolean -> code_based
    Text (long strings, high cardinality) -> llm_judge
    Categorical -> code_based
    Mixed/unknown -> code_based (conservative)

    Returns:
        "code_based" or "llm_judge"
    """
    col_type = col_types.get(col_name, "unknown")
    if col_type in ("numeric", "datetime", "boolean", "categorical"):
        return "code_based"
    if col_type == "text":
        return "llm_judge"
    # mixed / empty / unknown -> code-based (cheap, conservative)
    return "code_based"


# ──────────────────────────────────────────────────────────────
# Code-Based Checks
# ──────────────────────────────────────────────────────────────

def run_null_rate_check(series: pd.Series, max_rate: float) -> dict:
    """
    Check that the null rate is within the configured limit.

    Returns:
        check result dict with pass/fail, observed_rate, threshold
    """
    total = len(series)
    null_count = int(series.isna().sum())
    observed_rate = round(null_count / total, 6) if total > 0 else 0.0
    passed = observed_rate <= max_rate
    return {
        "check": "null_rate",
        "pass": passed,
        "observed_rate": observed_rate,
        "threshold": max_rate,
        "null_count": null_count,
        "total": total,
    }


def run_distribution_match_check(
    synth_series: pd.Series,
    orig_series: Optional[pd.Series],
    test: str,
    min_pvalue: float,
    col_type: str,
) -> dict:
    """
    Run a statistical distribution match check.

    For numeric columns: KS test (or as configured).
    For categorical columns: chi-square test.
    For text columns: KS test on character length distribution.

    Returns:
        check result dict
    """
    if orig_series is None:
        return {
            "check": "distribution_match",
            "pass": None,
            "note": "No original data provided; distribution check skipped",
        }

    # Determine effective test type
    effective_test = test
    if effective_test == "auto":
        if col_type in ("numeric",):
            effective_test = "ks"
        elif col_type == "categorical":
            effective_test = "chi_square"
        else:
            # Text: use KS on lengths
            effective_test = "ks_length"

    if effective_test == "ks":
        result = ks_test(orig_series, synth_series)
        result["check"] = "distribution_match"
        result["test_used"] = "ks"
        result["min_pvalue"] = min_pvalue
        if result.get("p_value") is not None:
            result["pass"] = result["p_value"] >= min_pvalue
        return result

    if effective_test == "chi_square":
        result = chi_square_test(orig_series, synth_series)
        result["check"] = "distribution_match"
        result["test_used"] = "chi_square"
        result["min_pvalue"] = min_pvalue
        if result.get("p_value") is not None:
            result["pass"] = result["p_value"] >= min_pvalue
        return result

    if effective_test == "ks_length":
        # Compare length distributions for text columns
        orig_lengths = orig_series.dropna().astype(str).str.len().rename("length")
        synth_lengths = synth_series.dropna().astype(str).str.len().rename("length")
        result = ks_test(orig_lengths, synth_lengths)
        result["check"] = "distribution_match"
        result["test_used"] = "ks_length"
        result["min_pvalue"] = min_pvalue
        if result.get("p_value") is not None:
            result["pass"] = result["p_value"] >= min_pvalue
        return result

    return {
        "check": "distribution_match",
        "pass": None,
        "note": f"Unknown test type: {test}",
    }


def run_value_range_check(series: pd.Series, min_val: Optional[float], max_val: Optional[float]) -> dict:
    """
    Check that all values fall within [min_val, max_val].

    Returns:
        check result dict with flagged row indices
    """
    result = check_value_range(series, min_val=min_val, max_val=max_val)
    result["check"] = "value_range"

    # Collect flagged row indices (up to 100)
    numeric = pd.to_numeric(series.dropna(), errors="coerce").dropna()
    flagged_indices = []
    if min_val is not None:
        below_mask = numeric < min_val
        flagged_indices.extend(numeric[below_mask].index.tolist())
    if max_val is not None:
        above_mask = numeric > max_val
        flagged_indices.extend(numeric[above_mask].index.tolist())

    result["flagged_indices"] = sorted(set(int(i) for i in flagged_indices))[:100]
    return result


def run_allowed_values_check(series: pd.Series, allowed: list) -> dict:
    """
    Check that all values are in the allowed set.

    Returns:
        check result dict with violation count and flagged indices
    """
    non_null = series.dropna()
    total = len(non_null)
    allowed_set = set(str(v) for v in allowed)
    str_vals = non_null.astype(str)
    violations = str_vals[~str_vals.isin(allowed_set)]
    violation_count = len(violations)
    passed = violation_count == 0

    return {
        "check": "allowed_values",
        "pass": passed,
        "total": total,
        "violation_count": violation_count,
        "violation_rate": round(violation_count / total, 6) if total > 0 else 0.0,
        "flagged_indices": sorted(int(i) for i in violations.index.tolist())[:100],
        "sample_violations": violations.head(10).tolist(),
    }


def run_schema_conformance_check(series: pd.Series, schema: dict) -> dict:
    """
    Check schema conformance: type, non-null, non-empty, min/max length, regex, allowed values.

    Schema keys (all optional):
        "non_null": bool
        "non_empty": bool (for strings)
        "dtype": str — expected dtype family ("numeric", "string", "integer")
        "min_length": int — minimum string length
        "max_length": int — maximum string length
        "regex": str — regex pattern that values must match
        "allowed_values": list

    Returns:
        check result dict
    """
    total = len(series)
    violations = []
    flagged_indices = set()

    # Non-null check
    if schema.get("non_null", False):
        null_mask = series.isna()
        null_count = int(null_mask.sum())
        if null_count > 0:
            violations.append({
                "rule": "non_null",
                "violation_count": null_count,
                "violation_rate": round(null_count / total, 6) if total > 0 else 0.0,
            })
            flagged_indices.update(series[null_mask].index.tolist())

    str_vals = series.dropna().astype(str)

    # Non-empty check
    if schema.get("non_empty", False):
        empty_mask = str_vals.str.strip() == ""
        empty_count = int(empty_mask.sum())
        if empty_count > 0:
            violations.append({
                "rule": "non_empty",
                "violation_count": empty_count,
                "violation_rate": round(empty_count / len(str_vals), 6) if len(str_vals) > 0 else 0.0,
            })
            flagged_indices.update(str_vals[empty_mask].index.tolist())

    # Min/max length
    if "min_length" in schema or "max_length" in schema:
        lengths = str_vals.str.len()
        if "min_length" in schema:
            short = str_vals[lengths < schema["min_length"]]
            if len(short) > 0:
                violations.append({
                    "rule": "min_length",
                    "threshold": schema["min_length"],
                    "violation_count": len(short),
                })
                flagged_indices.update(short.index.tolist())
        if "max_length" in schema:
            long_vals = str_vals[lengths > schema["max_length"]]
            if len(long_vals) > 0:
                violations.append({
                    "rule": "max_length",
                    "threshold": schema["max_length"],
                    "violation_count": len(long_vals),
                })
                flagged_indices.update(long_vals.index.tolist())

    # Regex check
    if "regex" in schema:
        pattern = re.compile(schema["regex"])
        mismatch = str_vals[~str_vals.str.match(pattern)]
        if len(mismatch) > 0:
            violations.append({
                "rule": "regex",
                "pattern": schema["regex"],
                "violation_count": len(mismatch),
                "sample_violations": mismatch.head(5).tolist(),
            })
            flagged_indices.update(mismatch.index.tolist())

    # Allowed values
    if "allowed_values" in schema:
        allowed_set = set(str(v) for v in schema["allowed_values"])
        bad = str_vals[~str_vals.isin(allowed_set)]
        if len(bad) > 0:
            violations.append({
                "rule": "allowed_values",
                "allowed": schema["allowed_values"][:20],
                "violation_count": len(bad),
                "sample_violations": bad.head(5).tolist(),
            })
            flagged_indices.update(bad.index.tolist())

    passed = len(violations) == 0
    return {
        "check": "schema_conformance",
        "pass": passed,
        "total": total,
        "violation_rules": violations,
        "flagged_indices": sorted(int(i) for i in flagged_indices)[:100],
    }


def run_correlation_check(
    df: pd.DataFrame,
    col_name: str,
    correlation_with: dict,
) -> dict:
    """
    Check correlation between a numeric column and another column in the DataFrame.

    correlation_with format: {"column": "other_col", "min_r": 0.7, "method": "pearson"}

    Returns:
        check result dict
    """
    other_col = correlation_with.get("column")
    min_r = correlation_with.get("min_r", 0.5)
    method = correlation_with.get("method", "pearson")

    if not other_col or other_col not in df.columns:
        return {
            "check": "correlation",
            "pass": None,
            "note": f"Correlation target column '{other_col}' not found in dataset",
        }

    col_num = pd.to_numeric(df[col_name].dropna(), errors="coerce").dropna()
    other_num = pd.to_numeric(df[other_col].dropna(), errors="coerce").dropna()

    # Align indices
    common_idx = col_num.index.intersection(other_num.index)
    if len(common_idx) < 2:
        return {
            "check": "correlation",
            "pass": None,
            "note": "Insufficient overlapping numeric values for correlation",
        }

    a = col_num.loc[common_idx]
    b = other_num.loc[common_idx]

    if method == "spearman":
        from scipy import stats
        r, p_value = stats.spearmanr(a, b)
    else:
        r = float(a.corr(b, method="pearson"))
        p_value = None

    passed = abs(r) >= min_r
    result = {
        "check": "correlation",
        "pass": passed,
        "column": col_name,
        "correlated_with": other_col,
        "method": method,
        "observed_r": round(r, 6),
        "min_r": min_r,
        "n": len(common_idx),
    }
    if p_value is not None:
        result["p_value"] = round(float(p_value), 6)
    return result


def run_vocabulary_overlap_check(
    synth_series: pd.Series,
    orig_series: Optional[pd.Series],
    min_jaccard: float = 0.3,
) -> dict:
    """
    Check vocabulary overlap between synthetic and original text columns.

    Returns:
        check result dict
    """
    if orig_series is None:
        return {
            "check": "vocabulary_overlap",
            "pass": None,
            "note": "No original data provided; vocabulary check skipped",
        }

    result = vocabulary_overlap(orig_series, synth_series)
    result["check"] = "vocabulary_overlap"
    result["min_jaccard"] = min_jaccard
    result["pass"] = result.get("jaccard_similarity", 0.0) >= min_jaccard
    return result


# ──────────────────────────────────────────────────────────────
# Sentinel Check (global across all columns)
# ──────────────────────────────────────────────────────────────

def run_sentinel_check(df: pd.DataFrame, columns: list[str], patterns: list[str]) -> dict:
    """
    Scan all requested columns for regenerated sentinel values.

    Returns:
        dict with per-column sentinel detection results and overall summary
    """
    column_results = {}
    total_sentinel_count = 0

    for col in columns:
        if col not in df.columns:
            continue
        result = detect_sentinels(df[col], patterns=patterns)
        column_results[col] = result
        total_sentinel_count += result.get("sentinel_count", 0)

    overall_pass = total_sentinel_count == 0
    return {
        "pass": overall_pass,
        "total_sentinel_count": total_sentinel_count,
        "patterns_checked": patterns,
        "columns": column_results,
    }


# ──────────────────────────────────────────────────────────────
# Code-Based Column Validation
# ──────────────────────────────────────────────────────────────

def validate_column_code_based(
    col_name: str,
    df: pd.DataFrame,
    orig_df: Optional[pd.DataFrame],
    checks_config: dict,
    col_type: str,
) -> dict:
    """
    Run all code-based checks for a column based on checks_config.

    Supported check keys in checks_config:
        "null_rate": {"max": float}
        "value_range": {"min": float, "max": float}
        "distribution_match": {"test": "ks"|"chi_square"|"ks_length"|"auto", "min_pvalue": float}
        "vocabulary_overlap": {"min_jaccard": float}
        "schema_conformance": {schema dict}
        "allowed_values": [list]
        "correlation": {"column": str, "min_r": float, "method": str}

    Returns:
        dict with per-check results, pass, score, flagged_rows, suggestions
    """
    series = df[col_name] if col_name in df.columns else pd.Series([], dtype=object)
    orig_series = orig_df[col_name] if (orig_df is not None and col_name in orig_df.columns) else None

    check_results = {}
    flagged_indices = set()
    failed_checks = []

    # Null rate
    if "null_rate" in checks_config:
        cfg = checks_config["null_rate"]
        max_rate = cfg.get("max", DEFAULT_MAX_NULL_RATE)
        r = run_null_rate_check(series, max_rate=max_rate)
        check_results["null_rate"] = r
        if not r["pass"]:
            failed_checks.append("null_rate")

    # Value range
    if "value_range" in checks_config:
        cfg = checks_config["value_range"]
        r = run_value_range_check(series, min_val=cfg.get("min"), max_val=cfg.get("max"))
        check_results["value_range"] = r
        if not r["pass"]:
            failed_checks.append("value_range")
            flagged_indices.update(r.get("flagged_indices", []))

    # Distribution match
    if "distribution_match" in checks_config:
        cfg = checks_config["distribution_match"]
        r = run_distribution_match_check(
            synth_series=series,
            orig_series=orig_series,
            test=cfg.get("test", "auto"),
            min_pvalue=cfg.get("min_pvalue", DEFAULT_MIN_KS_PVALUE),
            col_type=col_type,
        )
        check_results["distribution_match"] = r
        if r.get("pass") is False:
            failed_checks.append("distribution_match")

    # Vocabulary overlap
    if "vocabulary_overlap" in checks_config:
        cfg = checks_config["vocabulary_overlap"]
        r = run_vocabulary_overlap_check(
            synth_series=series,
            orig_series=orig_series,
            min_jaccard=cfg.get("min_jaccard", 0.3),
        )
        check_results["vocabulary_overlap"] = r
        if r.get("pass") is False:
            failed_checks.append("vocabulary_overlap")

    # Schema conformance
    if "schema_conformance" in checks_config:
        r = run_schema_conformance_check(series, schema=checks_config["schema_conformance"])
        check_results["schema_conformance"] = r
        if not r["pass"]:
            failed_checks.append("schema_conformance")
            flagged_indices.update(r.get("flagged_indices", []))

    # Allowed values shorthand
    if "allowed_values" in checks_config:
        r = run_allowed_values_check(series, allowed=checks_config["allowed_values"])
        check_results["allowed_values"] = r
        if not r["pass"]:
            failed_checks.append("allowed_values")
            flagged_indices.update(r.get("flagged_indices", []))

    # Correlation
    if "correlation" in checks_config:
        r = run_correlation_check(df, col_name, checks_config["correlation"])
        check_results["correlation"] = r
        if r.get("pass") is False:
            failed_checks.append("correlation")

    # Compute score: fraction of checks that passed
    total_checks = len(check_results)
    # Count definitive pass/fail only (skip None-pass checks)
    definitive = [(k, v) for k, v in check_results.items() if v.get("pass") is not None]
    passed_count = sum(1 for _, v in definitive if v.get("pass") is True)
    score = round(passed_count / len(definitive), 4) if definitive else 1.0

    column_pass = len(failed_checks) == 0

    # Build flagged rows list
    flagged_rows = []
    for idx in sorted(flagged_indices)[:100]:
        try:
            val = df.at[idx, col_name]
        except (KeyError, IndexError):
            val = None
        flagged_rows.append({
            "row_index": int(idx),
            "value": str(val) if val is not None else None,
            "failed_checks": failed_checks,
        })

    # Generate suggestions
    suggestions = _generate_code_based_suggestions(failed_checks, check_results, col_type)

    return {
        "approach": "code_based",
        "col_type": col_type,
        "checks": check_results,
        "failed_checks": failed_checks,
        "pass": column_pass,
        "score": score,
        "flagged_rows": flagged_rows,
        "suggestions": suggestions,
    }


def _generate_code_based_suggestions(
    failed_checks: list[str],
    check_results: dict,
    col_type: str,
) -> list[str]:
    """Generate actionable suggestions based on failed code-based checks."""
    suggestions = []

    if "null_rate" in failed_checks:
        r = check_results["null_rate"]
        suggestions.append(
            f"High null rate ({r['observed_rate']:.1%}): add 'non-null output required' to agent "
            f"instruction; set target_rows=fill-missing in batch_synthesize to re-fill null rows."
        )

    if "value_range" in failed_checks:
        for v in check_results["value_range"].get("violations", []):
            if v["type"] == "below_min":
                suggestions.append(
                    f"Values below minimum {v['limit']} (min observed: {v['min_observed']}): "
                    f"add explicit range constraint to synthesis prompt. Example: "
                    f"'Value must be >= {v['limit']}.'"
                )
            elif v["type"] == "above_max":
                suggestions.append(
                    f"Values above maximum {v['limit']} (max observed: {v['max_observed']}): "
                    f"add explicit range constraint to synthesis prompt. Example: "
                    f"'Value must be <= {v['limit']}.'"
                )

    if "distribution_match" in failed_checks:
        r = check_results["distribution_match"]
        suggestions.append(
            f"Distribution mismatch (p-value={r.get('p_value', 'N/A')}): increase few-shot "
            f"examples from original data, or use statistical_sample strategy for this column."
        )

    if "vocabulary_overlap" in failed_checks:
        r = check_results["vocabulary_overlap"]
        suggestions.append(
            f"Low vocabulary overlap (jaccard={r.get('jaccard_similarity', 'N/A')}): include "
            f"domain-specific terminology in agent instructions; add reference data from original."
        )

    if "schema_conformance" in failed_checks:
        r = check_results["schema_conformance"]
        for rule in r.get("violation_rules", []):
            suggestions.append(
                f"Schema violation ({rule['rule']}): enforce in agent instruction. "
                f"Example: add output format constraints and validation step."
            )

    if "allowed_values" in failed_checks:
        r = check_results["allowed_values"]
        suggestions.append(
            f"Out-of-set values ({r['violation_count']} violations): add allowed values list "
            f"explicitly to the synthesis prompt."
        )

    if "correlation" in failed_checks:
        r = check_results["correlation"]
        suggestions.append(
            f"Low correlation with '{r.get('correlated_with')}' "
            f"(r={r.get('observed_r', 'N/A')}, required >= {r.get('min_r')}): include the "
            f"correlated column as a context dependency in synthesis config."
        )

    return suggestions


# ──────────────────────────────────────────────────────────────
# LLM-as-Judge Column Validation
# ──────────────────────────────────────────────────────────────

def build_judge_prompt(
    col_name: str,
    rubric: str,
    row: dict,
    value: Any,
) -> str:
    """
    Build a prompt for LLM-as-judge evaluation.

    Returns:
        Prompt string requesting JSON output: {"pass": bool, "score": float, "reason": str}
    """
    safe_row = sanitize_row_for_prompt(row, max_length=500)
    safe_value = str(value)[:1000] if value is not None else "(null)"

    # Remove target col from context to avoid circular reference
    context = {k: v for k, v in safe_row.items() if k != col_name}
    context_str = "\n".join(f"  {k}: {v}" for k, v in list(context.items())[:10])

    return f"""You are a data quality judge. Evaluate the synthesized value for column '{col_name}'.

Row context:
{context_str}

Synthesized value for '{col_name}':
{safe_value}

Evaluation rubric:
{rubric}

Respond ONLY with a JSON object (no markdown, no explanation):
{{"pass": true or false, "score": float between 0 and 1, "reason": "brief reason"}}"""


def validate_column_llm_judge(
    col_name: str,
    df: pd.DataFrame,
    rubric: str,
    sample_rate: float,
    pass_threshold: float,
    agent_yaml: Optional[str],
    model: Optional[str],
    cost_accumulator: CostAccumulator,
    sample_size: Optional[int] = None,
) -> dict:
    """
    Run LLM-as-judge evaluation on a sampled subset of rows.

    Args:
        col_name: Column to evaluate
        df: Synthetic DataFrame
        rubric: Rubric string for the judge
        sample_rate: Fraction of rows to sample (0–1)
        pass_threshold: Fraction of judged rows that must pass (0–1)
        agent_yaml: Path to agent YAML (or None to use inline config)
        model: Model override
        cost_accumulator: Cost tracker
        sample_size: Override sample count (ignores sample_rate if set)

    Returns:
        dict with judge results, pass, score, flagged_rows, suggestions
    """
    if col_name not in df.columns:
        return {
            "approach": "llm_judge",
            "pass": None,
            "score": None,
            "note": f"Column '{col_name}' not found in dataset",
            "flagged_rows": [],
            "suggestions": [],
        }

    series = df[col_name]
    non_null_idx = series.dropna().index.tolist()
    total_rows = len(non_null_idx)

    if total_rows == 0:
        return {
            "approach": "llm_judge",
            "pass": False,
            "score": 0.0,
            "note": "All values are null; cannot judge",
            "flagged_rows": [],
            "suggestions": ["All values are null. Re-run synthesis with fill-missing mode."],
        }

    # Determine sample count
    if sample_size is not None:
        n_sample = min(sample_size, total_rows)
    else:
        n_sample = max(1, min(total_rows, int(math.ceil(total_rows * sample_rate))))

    # Random sample (reproducible)
    rng = np.random.default_rng(42)
    sampled_indices = rng.choice(non_null_idx, size=n_sample, replace=False).tolist()

    # Build or load judge agent
    agent = _build_judge_agent(agent_yaml=agent_yaml, model=model)

    # Run judge on each sampled row
    judged_results = []
    flagged_rows = []

    for idx in sampled_indices:
        if cost_accumulator.max_cost is not None and not cost_accumulator.check_budget(0.001):
            logger.warning("Cost limit approaching; stopping LLM judge sampling early")
            break

        row = df.loc[idx].to_dict()
        value = row.get(col_name)

        prompt = build_judge_prompt(col_name=col_name, rubric=rubric, row=row, value=value)

        try:
            session_id = str(uuid.uuid4())
            response_text = run_agent(agent, prompt, session_id=session_id)

            # Parse JSON response
            judge_result = _parse_judge_response(response_text)

            # Track cost estimate
            estimated_cost = cost_accumulator.estimate_cost(
                prompt_tokens=len(prompt) // 4,
                completion_tokens=60,
                model=model or DEFAULT_MODEL,
            )
            cost_accumulator.total_usd += estimated_cost
            cost_accumulator.call_count += 1
            m_key = model or DEFAULT_MODEL
            cost_accumulator.costs_by_model[m_key] = (
                cost_accumulator.costs_by_model.get(m_key, 0.0) + estimated_cost
            )

            judged_results.append({
                "row_index": int(idx),
                "pass": judge_result.get("pass", False),
                "score": judge_result.get("score", 0.0),
                "reason": judge_result.get("reason", ""),
            })

            if not judge_result.get("pass", True):
                flagged_rows.append({
                    "row_index": int(idx),
                    "value": str(value)[:200] if value is not None else None,
                    "judge_score": judge_result.get("score"),
                    "judge_reason": judge_result.get("reason", ""),
                    "column": col_name,
                    "criterion": "llm_judge",
                })

        except CostLimitExceeded:
            raise
        except Exception as e:
            logger.warning("LLM judge failed for row %d, column '%s': %s", idx, col_name, e)
            judged_results.append({
                "row_index": int(idx),
                "pass": None,
                "score": None,
                "reason": f"Judge error: {e}",
                "error": True,
            })

    # Aggregate results
    definitive = [r for r in judged_results if r.get("pass") is not None]
    passed_count = sum(1 for r in definitive if r["pass"] is True)
    n_judged = len(definitive)

    pass_rate = round(passed_count / n_judged, 6) if n_judged > 0 else 0.0
    avg_score = round(
        sum(r["score"] for r in definitive if r.get("score") is not None)
        / max(1, sum(1 for r in definitive if r.get("score") is not None)),
        4,
    )

    column_pass = pass_rate >= pass_threshold

    # 95% confidence interval (normal approximation)
    confidence_interval = None
    if n_judged >= 10:
        margin = 1.96 * math.sqrt(pass_rate * (1 - pass_rate) / n_judged)
        confidence_interval = {
            "lower": round(max(0.0, pass_rate - margin), 4),
            "upper": round(min(1.0, pass_rate + margin), 4),
        }

    suggestions = _generate_judge_suggestions(pass_rate, pass_threshold, col_name, flagged_rows)

    return {
        "approach": "llm_judge",
        "rubric": rubric,
        "sample_size": n_sample,
        "total_rows": total_rows,
        "sample_rate": round(n_sample / total_rows, 4) if total_rows > 0 else 0.0,
        "n_judged": n_judged,
        "pass_rate": pass_rate,
        "pass_threshold": pass_threshold,
        "avg_score": avg_score,
        "pass": column_pass,
        "score": pass_rate,
        "confidence_interval": confidence_interval,
        "judged_sample": judged_results,
        "flagged_rows": flagged_rows[:50],  # cap for report size
        "suggestions": suggestions,
    }


def _build_judge_agent(agent_yaml: Optional[str], model: Optional[str]):
    """Build or create a judge agent from YAML or inline config."""
    if agent_yaml and Path(agent_yaml).exists():
        return build_agent(agent_yaml, model_override=model)

    # Create inline config
    import tempfile
    import yaml

    resolved_model = model or DEFAULT_MODEL
    config = {
        "name": "validate_judge",
        "model": resolved_model,
        "instruction": (
            "You are a data quality judge. Evaluate synthesized data values against the given "
            "rubric. Always respond with a valid JSON object: "
            '{\"pass\": bool, \"score\": 0.0-1.0, \"reason\": \"brief explanation\"}'
        ),
    }

    # Write to a temp file
    tmp = tempfile.NamedTemporaryFile(
        mode="w", suffix=".yaml", delete=False, prefix="judge_agent_"
    )
    yaml.safe_dump(config, tmp)
    tmp.flush()
    tmp.close()

    return build_agent(tmp.name, model_override=resolved_model)


def _parse_judge_response(response_text: str) -> dict:
    """
    Parse judge LLM response into a structured dict.

    Handles JSON embedded in text or markdown code fences.
    Falls back to heuristic parsing on failure.
    """
    text = response_text.strip()

    # Strip markdown code fences
    if "```" in text:
        text = re.sub(r"```(?:json)?\n?", "", text).strip()
        text = text.rstrip("`").strip()

    # Try direct JSON parse
    try:
        result = json.loads(text)
        if isinstance(result, dict):
            return result
    except json.JSONDecodeError:
        pass

    # Try to extract JSON substring
    match = re.search(r"\{[^}]+\}", text, re.DOTALL)
    if match:
        try:
            result = json.loads(match.group())
            if isinstance(result, dict):
                return result
        except json.JSONDecodeError:
            pass

    # Heuristic fallback
    lower = text.lower()
    passed = "pass" in lower and "fail" not in lower and "false" not in lower
    score = 0.8 if passed else 0.2

    return {
        "pass": passed,
        "score": score,
        "reason": text[:200],
        "parse_fallback": True,
    }


def _generate_judge_suggestions(
    pass_rate: float,
    pass_threshold: float,
    col_name: str,
    flagged_rows: list[dict],
) -> list[str]:
    """Generate actionable suggestions based on LLM judge results."""
    suggestions = []

    if pass_rate < pass_threshold:
        gap = pass_threshold - pass_rate
        suggestions.append(
            f"LLM judge pass rate ({pass_rate:.1%}) is below threshold ({pass_threshold:.1%}). "
            f"Gap: {gap:.1%}. Recommended actions:"
        )
        suggestions.append(
            "  - Add more domain-specific few-shot examples to the synthesis prompt."
        )
        suggestions.append(
            "  - Lower temperature or increase max_tokens for the synthesis model."
        )
        suggestions.append(
            f"  - Add explicit quality instructions to agent YAML for column '{col_name}'."
        )
        if flagged_rows:
            sample_reasons = list(set(
                r.get("judge_reason", "") for r in flagged_rows[:5] if r.get("judge_reason")
            ))
            if sample_reasons:
                suggestions.append(
                    f"  - Common failure reasons: {'; '.join(sample_reasons[:3])}"
                )

    return suggestions


# ──────────────────────────────────────────────────────────────
# Combined (code_based + llm_judge) Column Validation
# ──────────────────────────────────────────────────────────────

def validate_column_combined(
    col_name: str,
    df: pd.DataFrame,
    orig_df: Optional[pd.DataFrame],
    checks_config: dict,
    rubric: str,
    sample_rate: float,
    pass_threshold: float,
    col_type: str,
    agent_yaml: Optional[str],
    model: Optional[str],
    cost_accumulator: CostAccumulator,
    sample_size: Optional[int] = None,
) -> dict:
    """
    Run code-based checks first, then LLM-as-judge on rows that pass code checks.

    Returns merged result dict.
    """
    # Step 1: Code-based checks
    code_result = validate_column_code_based(
        col_name=col_name,
        df=df,
        orig_df=orig_df,
        checks_config=checks_config,
        col_type=col_type,
    )

    # Filter to rows that passed code checks (not flagged)
    flagged_code_indices = set(r["row_index"] for r in code_result.get("flagged_rows", []))
    passing_df = df[~df.index.isin(flagged_code_indices)]

    # Step 2: LLM-as-judge on passing rows
    judge_result = validate_column_llm_judge(
        col_name=col_name,
        df=passing_df,
        rubric=rubric,
        sample_rate=sample_rate,
        pass_threshold=pass_threshold,
        agent_yaml=agent_yaml,
        model=model,
        cost_accumulator=cost_accumulator,
        sample_size=sample_size,
    )

    # Merge results
    combined_pass = code_result["pass"] and judge_result.get("pass", True)
    combined_score = round(
        (code_result["score"] + (judge_result.get("score") or 1.0)) / 2, 4
    )

    flagged_rows = code_result.get("flagged_rows", []) + judge_result.get("flagged_rows", [])
    suggestions = code_result.get("suggestions", []) + judge_result.get("suggestions", [])

    return {
        "approach": "combined",
        "col_type": col_type,
        "code_based": code_result,
        "llm_judge": judge_result,
        "pass": combined_pass,
        "score": combined_score,
        "flagged_rows": flagged_rows[:100],
        "suggestions": suggestions,
    }


# ──────────────────────────────────────────────────────────────
# Main Validation Orchestrator
# ──────────────────────────────────────────────────────────────

def validate_dataset(
    df: pd.DataFrame,
    orig_df: Optional[pd.DataFrame],
    columns: list[str],
    criteria: Optional[dict],
    sentinel_patterns: list[str],
    agent_yaml: Optional[str],
    model: Optional[str],
    cost_accumulator: CostAccumulator,
    llm_sample_size: Optional[int] = None,
) -> dict:
    """
    Orchestrate full dataset validation.

    For each column:
    1. Determine approach (from criteria or auto-detect)
    2. Run code-based, llm_judge, or combined checks
    3. Collect per-column results

    Returns:
        Full report dict (pre-summary)
    """
    col_types = detect_column_types(df)
    column_reports = {}

    # Global sentinel check
    sentinel_report = run_sentinel_check(df, columns, sentinel_patterns)

    for col_name in columns:
        logger.info("Validating column: %s", col_name)

        if col_name not in df.columns:
            column_reports[col_name] = {
                "approach": "skipped",
                "pass": None,
                "score": None,
                "note": f"Column '{col_name}' not found in dataset",
                "flagged_rows": [],
                "suggestions": [],
            }
            continue

        col_type = col_types.get(col_name, "unknown")

        # Resolve approach and config from criteria
        col_criteria = {}
        if criteria and "columns" in criteria:
            col_criteria = criteria["columns"].get(col_name, {})

        approach = col_criteria.get("approach", "auto")
        if approach == "auto":
            approach = detect_approach(col_name, df, col_types)

        checks_config = col_criteria.get("checks", {})
        rubric = col_criteria.get("rubric", "")
        sample_rate = col_criteria.get("sample_rate", DEFAULT_SAMPLE_RATE)
        pass_threshold = col_criteria.get("pass_threshold", DEFAULT_PASS_THRESHOLD)

        try:
            if approach == "code_based":
                result = validate_column_code_based(
                    col_name=col_name,
                    df=df,
                    orig_df=orig_df,
                    checks_config=checks_config,
                    col_type=col_type,
                )

            elif approach == "llm_judge":
                if not rubric:
                    rubric = (
                        f"Rate the quality of the synthesized '{col_name}' value on a scale "
                        f"of 0 to 1: relevance (0-1), accuracy (0-1), completeness (0-1). "
                        f"Pass if overall quality >= 0.6."
                    )
                result = validate_column_llm_judge(
                    col_name=col_name,
                    df=df,
                    rubric=rubric,
                    sample_rate=sample_rate,
                    pass_threshold=pass_threshold,
                    agent_yaml=agent_yaml,
                    model=model,
                    cost_accumulator=cost_accumulator,
                    sample_size=llm_sample_size,
                )

            elif approach == "combined":
                if not rubric:
                    rubric = (
                        f"Rate the quality of the synthesized '{col_name}' value: "
                        f"accuracy, completeness, relevance (0-1 each). Pass if all >= 0.6."
                    )
                result = validate_column_combined(
                    col_name=col_name,
                    df=df,
                    orig_df=orig_df,
                    checks_config=checks_config,
                    rubric=rubric,
                    sample_rate=sample_rate,
                    pass_threshold=pass_threshold,
                    col_type=col_type,
                    agent_yaml=agent_yaml,
                    model=model,
                    cost_accumulator=cost_accumulator,
                    sample_size=llm_sample_size,
                )

            else:
                result = {
                    "approach": approach,
                    "pass": None,
                    "score": None,
                    "note": f"Unknown approach '{approach}'; skipped",
                    "flagged_rows": [],
                    "suggestions": [f"Use approach: code_based, llm_judge, combined, or auto"],
                }

        except CostLimitExceeded:
            raise
        except Exception as e:
            logger.error("Validation failed for column '%s': %s", col_name, e)
            result = {
                "approach": approach,
                "pass": None,
                "score": None,
                "error": str(e),
                "flagged_rows": [],
                "suggestions": [f"Validation error on column '{col_name}': {e}"],
            }

        column_reports[col_name] = result

    return column_reports, sentinel_report


# ──────────────────────────────────────────────────────────────
# Report Assembly
# ──────────────────────────────────────────────────────────────

def assemble_report(
    column_reports: dict,
    sentinel_report: dict,
    df: pd.DataFrame,
    orig_df: Optional[pd.DataFrame],
    columns: list[str],
    cost_accumulator: CostAccumulator,
    elapsed_seconds: float,
    sample_size: Optional[int],
    metadata: dict,
) -> dict:
    """
    Assemble the final structured validation report.

    Returns:
        Full report dict matching the specified structure
    """
    # Determine per-column pass/fail
    col_verdicts = []
    for col_name in columns:
        col_result = column_reports.get(col_name, {})
        col_pass = col_result.get("pass")
        if col_pass is True:
            col_verdicts.append(1.0)
        elif col_pass is False:
            col_verdicts.append(0.0)
        # None = skip (unknown/error)

    # Compute column-level scores
    col_scores = []
    for col_name in columns:
        col_result = column_reports.get(col_name, {})
        score = col_result.get("score")
        if score is not None:
            col_scores.append(score)

    # Overall verdict
    definitive_verdicts = [v for col_name in columns
                           for v in [column_reports.get(col_name, {}).get("pass")]
                           if v is not None]

    sentinel_pass = sentinel_report.get("pass", True)
    all_pass = all(v is True for v in definitive_verdicts) and sentinel_pass

    overall_score = round(sum(col_scores) / len(col_scores), 4) if col_scores else 1.0
    overall_verdict = "PASS" if all_pass else "FAIL"

    # Summary counts
    passed_cols = sum(1 for col in columns if column_reports.get(col, {}).get("pass") is True)
    failed_cols = sum(1 for col in columns if column_reports.get(col, {}).get("pass") is False)
    error_cols = sum(1 for col in columns if column_reports.get(col, {}).get("pass") is None)

    summary = {
        "total_columns": len(columns),
        "columns_pass": passed_cols,
        "columns_fail": failed_cols,
        "columns_error_or_skipped": error_cols,
        "sentinel_check_pass": sentinel_pass,
        "total_rows": len(df),
        "original_rows": len(orig_df) if orig_df is not None else None,
        "sample_size": sample_size,
        "elapsed_seconds": round(elapsed_seconds, 2),
        "cost": cost_accumulator.summary(),
        "validated_at": datetime.now(timezone.utc).isoformat(),
    }

    report = {
        "success": True,
        "overall_verdict": overall_verdict,
        "overall_score": overall_score,
        "columns": column_reports,
        "sentinel_check": sentinel_report,
        "summary": summary,
    }

    # Merge any caller-provided metadata
    if metadata:
        report["metadata"] = metadata

    return report


# ──────────────────────────────────────────────────────────────
# CLI
# ──────────────────────────────────────────────────────────────

def parse_args(argv: Optional[list[str]] = None) -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(
        description=(
            "Scenario-adaptive validation of synthetic data. "
            "Supports code-based (statistical), LLM-as-judge, or combined approaches."
        )
    )

    # Positional
    parser.add_argument(
        "input_path",
        help="Path to synthetic data file to validate (CSV, Parquet, JSON, JSONL)",
    )
    parser.add_argument(
        "report_path",
        help="Path to write the JSON validation report",
    )

    # Optional inputs
    parser.add_argument(
        "--original-path",
        type=str,
        default=None,
        help="Path to original (reference) data file for distribution comparison",
    )
    parser.add_argument(
        "--criteria-json",
        type=str,
        default=None,
        help="Path to agent-generated JSON criteria file",
    )
    parser.add_argument(
        "--sentinel-patterns",
        type=str,
        default=None,
        help='JSON array of sentinel patterns to detect, e.g. \'["X","N/A","TBD"]\'',
    )
    parser.add_argument(
        "--columns",
        type=str,
        default=None,
        help="Comma-separated list of columns to validate (default: all columns)",
    )
    parser.add_argument(
        "--sample-size",
        type=int,
        default=None,
        help="Validate on a random subset of N rows (preview mode)",
    )
    parser.add_argument(
        "--max-cost",
        type=float,
        default=None,
        help="Maximum total LLM cost in USD; abort when exceeded",
    )
    parser.add_argument(
        "--agent-yaml",
        type=str,
        default=None,
        help="Path to LLM agent YAML config for LLM-as-judge evaluation",
    )
    parser.add_argument(
        "--model",
        type=str,
        default=None,
        help="LLM model override (e.g., openai/gpt-4o-mini)",
    )

    return parser.parse_args(argv)


def main(argv: Optional[list[str]] = None):
    """Main entry point."""
    args = parse_args(argv)

    # Configure logging
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(message)s",
        stream=sys.stderr,
    )

    start_time = time.time()

    # ── 1. Load synthetic data ───────────────────────────────
    try:
        df = load_dataframe(args.input_path)
    except FileNotFoundError:
        output_result(format_error(
            f"Input file not found: {args.input_path}",
            suggestion="Check the input file path",
        ))
        return
    except Exception as e:
        output_result(format_error(
            f"Failed to load input file: {e}",
            suggestion="Check file format (CSV, Parquet, JSON, JSONL supported)",
        ))
        return

    rows_in = len(df)
    logger.info("Loaded %d rows from %s", rows_in, args.input_path)

    if rows_in == 0:
        output_result(format_error(
            "Input file is empty",
            suggestion="Provide a non-empty synthetic data file",
        ))
        return

    # ── 2. Load original data (optional) ────────────────────
    orig_df = None
    if args.original_path:
        try:
            orig_df = load_dataframe(args.original_path)
            logger.info("Loaded %d original rows from %s", len(orig_df), args.original_path)
        except Exception as e:
            logger.warning("Could not load original data from %s: %s", args.original_path, e)

    # ── 3. Parse criteria JSON (optional) ───────────────────
    criteria = None
    if args.criteria_json:
        try:
            with open(args.criteria_json, "r") as f:
                criteria = json.load(f)
        except FileNotFoundError:
            output_result(format_error(
                f"Criteria JSON not found: {args.criteria_json}",
                suggestion="Check the --criteria-json path",
            ))
            return
        except json.JSONDecodeError as e:
            output_result(format_error(
                f"Invalid JSON in criteria file: {e}",
                suggestion="Ensure the criteria file contains valid JSON",
            ))
            return

    # ── 4. Parse sentinel patterns ───────────────────────────
    sentinel_patterns = DEFAULT_SENTINEL_PATTERNS
    if args.sentinel_patterns:
        try:
            parsed = json.loads(args.sentinel_patterns)
            if isinstance(parsed, list):
                sentinel_patterns = parsed
            else:
                logger.warning("--sentinel-patterns must be a JSON array; using defaults")
        except json.JSONDecodeError as e:
            logger.warning("Invalid JSON in --sentinel-patterns: %s; using defaults", e)

    # ── 5. Determine columns to validate ────────────────────
    if args.columns:
        columns = [c.strip() for c in args.columns.split(",") if c.strip()]
        # Warn about missing columns
        missing = [c for c in columns if c not in df.columns]
        if missing:
            logger.warning("Columns not found in data: %s", missing)
    else:
        # All columns, excluding synthesis metadata columns
        columns = [c for c in df.columns if not c.startswith("_synthesis_")]

    if not columns:
        output_result(format_error(
            "No columns to validate",
            suggestion="Check --columns or ensure input data has non-metadata columns",
        ))
        return

    logger.info("Validating %d columns: %s", len(columns), columns)

    # ── 6. Apply --sample-size ───────────────────────────────
    sample_size_used = None
    if args.sample_size and args.sample_size < rows_in:
        df = df.sample(n=args.sample_size, random_state=42).reset_index(drop=True)
        if orig_df is not None and args.sample_size < len(orig_df):
            orig_df = orig_df.sample(n=args.sample_size, random_state=42).reset_index(drop=True)
        sample_size_used = args.sample_size
        logger.info("Sampled %d rows for validation preview", sample_size_used)

    # ── 7. Initialize cost accumulator ──────────────────────
    cost_accumulator = CostAccumulator(max_cost=args.max_cost)

    # ── 8. Run validation ────────────────────────────────────
    cost_limit_hit = False
    try:
        column_reports, sentinel_report = validate_dataset(
            df=df,
            orig_df=orig_df,
            columns=columns,
            criteria=criteria,
            sentinel_patterns=sentinel_patterns,
            agent_yaml=args.agent_yaml,
            model=args.model,
            cost_accumulator=cost_accumulator,
            llm_sample_size=None,  # use sample_rate per column criteria
        )
    except CostLimitExceeded as e:
        logger.warning("Cost limit exceeded during validation: %s", e)
        cost_limit_hit = True
        # Build partial report
        column_reports = {}
        sentinel_report = {"pass": None, "note": "Aborted due to cost limit"}

    elapsed = time.time() - start_time

    # ── 9. Assemble report ───────────────────────────────────
    metadata = {
        "input_path": str(args.input_path),
        "original_path": str(args.original_path) if args.original_path else None,
        "criteria_json": str(args.criteria_json) if args.criteria_json else None,
        "model": args.model or DEFAULT_MODEL,
        "agent_yaml": args.agent_yaml,
        "sentinel_patterns": sentinel_patterns,
    }

    report = assemble_report(
        column_reports=column_reports,
        sentinel_report=sentinel_report,
        df=df,
        orig_df=orig_df,
        columns=columns,
        cost_accumulator=cost_accumulator,
        elapsed_seconds=elapsed,
        sample_size=sample_size_used,
        metadata=metadata,
    )

    if cost_limit_hit:
        report["success"] = False
        report["overall_verdict"] = "ABORTED"
        report["error"] = (
            f"Cost limit exceeded: ${cost_accumulator.total_usd:.4f} > ${args.max_cost:.4f}. "
            f"Partial validation results saved."
        )

    # ── 10. Write report ─────────────────────────────────────
    try:
        report_path = Path(args.report_path)
        report_path.parent.mkdir(parents=True, exist_ok=True)
        with open(report_path, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2, default=str)
        logger.info("Validation report written to %s", report_path)
    except Exception as e:
        output_result(format_error(
            f"Failed to write report: {e}",
            suggestion="Check the report path and write permissions",
        ))
        return

    # ── 11. Output summary to stdout ─────────────────────────
    passed_cols = report["summary"]["columns_pass"]
    failed_cols = report["summary"]["columns_fail"]
    verdict = report["overall_verdict"]

    summary_output = {
        "success": not cost_limit_hit,
        "report_path": str(args.report_path),
        "overall_verdict": verdict,
        "overall_score": report["overall_score"],
        "rows_validated": len(df),
        "sample_size": sample_size_used,
        "columns_pass": passed_cols,
        "columns_fail": failed_cols,
        "sentinel_check_pass": sentinel_report.get("pass"),
        "cost": cost_accumulator.summary(),
        "elapsed_seconds": round(elapsed, 2),
    }

    if cost_limit_hit:
        summary_output["error"] = report.get("error")
        print(json.dumps(summary_output, indent=2, default=str))
        sys.exit(COST_LIMIT_EXIT_CODE)

    output_result(summary_output)


if __name__ == "__main__":
    main()
