#!/usr/bin/env python3
"""
REFERENCE IMPLEMENTATION — generate_report.py
Generate Report - Assemble Markdown report from structured findings JSON
"""

import argparse
import json
import sys
from pathlib import Path
from datetime import datetime
try:
    from jinja2 import Template
except ImportError:
    Template = None  # jinja2 not installed — install with: pip install jinja2


STANDARD_TEMPLATE = """# {{ title }}

**Generated:** {{ timestamp }}

---

## Summary

{{ summary }}

---

## Data Provenance

**Source:** {{ data_source.file }}
**Rows:** {{ data_source.rows }}
**Columns:** {{ data_source.columns }}

{% if data_source.processing_steps %}
**Processing Steps:**
{% for step in data_source.processing_steps %}
- {{ step }}
{% endfor %}
{% endif %}

---

## Methodology

{{ methodology }}

{% if assumptions %}
**Assumptions:**
{% for assumption in assumptions %}
- {{ assumption }}
{% endfor %}
{% endif %}

---

## Key Findings

{% for i, finding in enumerate(key_findings, 1) %}
{{ i }}. **{{ finding.title }}**
   {{ finding.description }}
   {% if finding.evidence %}
   - *Evidence:* {{ finding.evidence }}
   {% endif %}
{% endfor %}

---

{% if visualizations %}
## Visualizations

{% for viz in visualizations %}
### {{ viz.caption }}

![{{ viz.caption }}]({{ viz.path }})

{% endfor %}

---
{% endif %}

## Caveats and Limitations

{% for caveat in caveats %}
- {{ caveat }}
{% endfor %}

---

## Next Steps

{% for step in next_steps %}
- {{ step }}
{% endfor %}

---

*Report generated by MAGIC Data Agent*
"""


EXECUTIVE_TEMPLATE = """# {{ title }}

**Date:** {{ timestamp }}

---

## Executive Summary

{{ summary }}

---

## Key Findings

{% for i, finding in enumerate(key_findings, 1) %}
**{{ i }}. {{ finding.title }}**
{{ finding.description }}
{% endfor %}

---

## Action Items

{% for step in next_steps %}
- {{ step }}
{% endfor %}

---

## Limitations

{% for caveat in caveats %}
- {{ caveat }}
{% endfor %}

---

## Data Overview

- **Source:** {{ data_source.file }}
- **Records Analyzed:** {{ data_source.rows }}
- **Columns:** {{ data_source.columns }}

---

*Executive report generated by MAGIC Data Agent*
"""


TECHNICAL_TEMPLATE = """# {{ title }}

**Generated:** {{ timestamp }}

---

## Abstract

{{ summary }}

---

## 1. Data Provenance

**Source File:** `{{ data_source.file }}`
**Dataset Dimensions:** {{ data_source.rows }} rows × {{ data_source.columns }} columns

{% if data_source.processing_steps %}
**Data Processing Pipeline:**
{% for step in data_source.processing_steps %}
{{ loop.index }}. {{ step }}
{% endfor %}
{% endif %}

---

## 2. Methodology

{{ methodology }}

{% if assumptions %}
### 2.1 Assumptions

{% for assumption in assumptions %}
- {{ assumption }}
{% endfor %}
{% endif %}

{% if profiling_summary %}
### 2.2 Data Profiling Summary

{{ profiling_summary }}
{% endif %}

{% if cleaning_summary %}
### 2.3 Data Cleaning Summary

{{ cleaning_summary }}
{% endif %}

---

## 3. Analysis Results

{% if analysis_results %}
{% for key, value in analysis_results.items() %}
### 3.{{ loop.index }} {{ key.replace('_', ' ').title() }}

```
{{ value }}
```

{% endfor %}
{% endif %}

---

## 4. Findings

{% for i, finding in enumerate(key_findings, 1) %}
### 4.{{ i }} {{ finding.title }}

{{ finding.description }}

{% if finding.evidence %}
**Evidence:** {{ finding.evidence }}
{% endif %}

{% if finding.statistics %}
**Statistical Details:**
```
{{ finding.statistics }}
```
{% endif %}

{% endfor %}

---

{% if visualizations %}
## 5. Visualizations

{% for viz in visualizations %}
### 5.{{ loop.index }} {{ viz.caption }}

![{{ viz.caption }}]({{ viz.path }})

{% if viz.description %}
{{ viz.description }}
{% endif %}

{% endfor %}

---
{% endif %}

## 6. Limitations and Caveats

{% for i, caveat in enumerate(caveats, 1) %}
{{ i }}. {{ caveat }}
{% endfor %}

---

## 7. Recommendations and Next Steps

{% for i, step in enumerate(next_steps, 1) %}
{{ i }}. {{ step }}
{% endfor %}

---

## References

- Analysis performed using MAGIC Data Agent
- Statistical computations verified against industry standards
- Visualization best practices based on Cleveland & McGill (1984)

---

*Technical report generated on {{ timestamp }}*
"""


def extract_summary(findings):
    """Extract or generate summary from findings."""
    if "summary" in findings and findings["summary"]:
        return findings["summary"]

    # Generate auto-summary
    summary_parts = []

    if "data_source" in findings:
        ds = findings["data_source"]
        summary_parts.append(
            f"Analysis of {ds.get('rows', 'N/A')} records "
            f"across {ds.get('columns', 'N/A')} variables."
        )

    if "key_findings" in findings and findings["key_findings"]:
        num_findings = len(findings["key_findings"])
        summary_parts.append(f"This report presents {num_findings} key findings.")

    if not summary_parts:
        summary_parts.append("Comprehensive data analysis report.")

    return " ".join(summary_parts)


def extract_methodology(findings):
    """Extract or generate methodology section."""
    if "methodology" in findings and findings["methodology"]:
        return findings["methodology"]

    # Generate from analysis results
    methods = []

    if "profiling_summary" in findings and findings["profiling_summary"]:
        methods.append("- **Data Profiling:** Comprehensive statistical profiling of all variables")

    if "cleaning_summary" in findings and findings["cleaning_summary"]:
        methods.append("- **Data Cleaning:** Quality assurance and data cleansing procedures")

    if "analysis_results" in findings and findings["analysis_results"]:
        for analysis_type in findings["analysis_results"].keys():
            methods.append(f"- **{analysis_type.replace('_', ' ').title()}:** Statistical analysis performed")

    if "visualizations" in findings and findings["visualizations"]:
        methods.append("- **Data Visualization:** Charts generated using best practices for clarity")

    if not methods:
        methods.append("- Statistical analysis performed on cleaned dataset")
        methods.append("- Results validated using standard methodologies")

    return "\n".join(methods)


def extract_key_findings(findings):
    """Extract and format key findings."""
    if "key_findings" in findings and findings["key_findings"]:
        # Ensure findings have required structure
        formatted_findings = []
        for finding in findings["key_findings"]:
            if isinstance(finding, str):
                formatted_findings.append({
                    "title": "Finding",
                    "description": finding,
                    "evidence": None
                })
            else:
                formatted_findings.append(finding)
        return formatted_findings

    # Generate placeholder if no findings
    return [{
        "title": "Analysis Complete",
        "description": "Statistical analysis has been performed on the dataset.",
        "evidence": "See detailed results in the analysis results section."
    }]


def extract_caveats(findings):
    """Extract caveats and limitations."""
    if "caveats" in findings and findings["caveats"]:
        return findings["caveats"]

    # Always include at least one caveat
    default_caveats = [
        "Results are based on the quality and completeness of the input data",
        "Statistical significance does not imply practical significance",
        "Correlations observed do not necessarily indicate causation"
    ]

    return default_caveats[:1]  # At least one caveat


def extract_next_steps(findings):
    """Extract or generate next steps."""
    if "next_steps" in findings and findings["next_steps"]:
        return findings["next_steps"]

    # Generate default next steps
    return [
        "Validate findings with domain experts",
        "Collect additional data to test hypotheses",
        "Monitor trends over time for temporal patterns"
    ]


def count_words(text):
    """Count words in text."""
    return len(text.split())


def main(findings_path: str, output_path: str,
         title: str = "Data Analysis Report",
         template: str = "standard") -> dict:
    """
    Assemble Markdown report from structured findings JSON.

    Args:
        findings_path: Path to input findings JSON file
        output_path: Path to output Markdown file
        title: Report title
        template: Template type (standard, executive, technical)

    Returns:
        Dictionary with success status and report metadata
    """
    try:
        # Read findings
        with open(findings_path, 'r') as f:
            findings = json.load(f)

        # Select template
        if template == "executive":
            template_str = EXECUTIVE_TEMPLATE
        elif template == "technical":
            template_str = TECHNICAL_TEMPLATE
        else:
            template_str = STANDARD_TEMPLATE

        # Extract components
        summary = extract_summary(findings)
        methodology = extract_methodology(findings)
        key_findings = extract_key_findings(findings)
        caveats = extract_caveats(findings)
        next_steps = extract_next_steps(findings)

        # Prepare context
        context = {
            "title": title,
            "timestamp": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            "summary": summary,
            "methodology": methodology,
            "key_findings": key_findings,
            "caveats": caveats,
            "next_steps": next_steps,
            "data_source": findings.get("data_source", {
                "file": "Unknown",
                "rows": "N/A",
                "columns": "N/A"
            }),
            "profiling_summary": findings.get("profiling_summary"),
            "cleaning_summary": findings.get("cleaning_summary"),
            "analysis_results": findings.get("analysis_results", {}),
            "visualizations": findings.get("visualizations", []),
            "assumptions": findings.get("assumptions", [])
        }

        # Render template
        jinja_template = Template(template_str)
        report_content = jinja_template.render(**context, enumerate=enumerate)

        # Write output
        Path(output_path).parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w') as f:
            f.write(report_content)

        # Count sections and words
        sections = []
        if template == "executive":
            sections = ["Executive Summary", "Key Findings", "Action Items", "Limitations", "Data Overview"]
        elif template == "technical":
            sections = ["Abstract", "Data Provenance", "Methodology", "Analysis Results",
                       "Findings", "Visualizations", "Limitations", "Recommendations"]
        else:
            sections = ["Summary", "Data Provenance", "Methodology", "Key Findings",
                       "Visualizations", "Caveats", "Next Steps"]

        word_count = count_words(report_content)
        charts_embedded = len(context["visualizations"])

        result = {
            "success": True,
            "output_path": output_path,
            "sections": sections,
            "word_count": word_count,
            "charts_embedded": charts_embedded
        }

        return result

    except FileNotFoundError:
        return {
            "success": False,
            "error": f"Findings file not found: {findings_path}",
            "suggestion": "Check the file path"
        }
    except json.JSONDecodeError as e:
        return {
            "success": False,
            "error": f"Invalid JSON in findings file: {e}",
            "suggestion": "Ensure findings file is valid JSON"
        }
    except Exception as e:
        return {
            "success": False,
            "error": str(e),
            "suggestion": "Check findings file format and parameters"
        }


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate Markdown report from findings JSON")
    parser.add_argument("findings_path", help="Path to input findings JSON file")
    parser.add_argument("output_path", help="Path to output Markdown file")
    parser.add_argument("--title", default="Data Analysis Report",
                       help="Report title")
    parser.add_argument("--template", default="standard",
                       choices=["standard", "executive", "technical"],
                       help="Template type")

    args = parser.parse_args()

    result = main(args.findings_path, args.output_path, args.title, args.template)
    print(json.dumps(result, indent=2, default=str))

    sys.exit(0 if result["success"] else 1)
